# Generated by Django 4.2.3 on 2023-08-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_application', '0001_initial'),
        ('cv_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='contact_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='contact_application.contactinfo'),
            preserve_default=False,
        ),
    ]
