# Generated by Django 4.2.3 on 2023-08-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_application', '0001_initial'),
        ('cv_application', '0006_cvmodel_skill_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='document_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='document_application.documentinfomodel'),
            preserve_default=False,
        ),
    ]
