# Generated by Django 4.2.3 on 2023-08-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_application', '0001_initial'),
        ('personal_info_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfomodel',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='location_application.locationmodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=256)),
                ('zip_code', models.CharField(max_length=256)),
                ('formatted_address', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('confidence_score', models.IntegerField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='location_application.locationmodel')),
            ],
        ),
        migrations.AddField(
            model_name='personalinfomodel',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='personal_info_application.addressmodel'),
            preserve_default=False,
        ),
    ]
