# Generated by Django 4.2.3 on 2023-08-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('state_iso_code', models.CharField()),
                ('country', models.CharField()),
                ('country_code', models.ManyToManyField(to='country_application.countrycode')),
            ],
        ),
    ]
