# Generated by Django 4.2.3 on 2023-08-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('confidence_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.CharField()),
                ('email_body', models.CharField()),
                ('email_reply_to', models.CharField()),
                ('email_signature', models.CharField()),
                ('email_form', models.CharField()),
                ('email_subject', models.CharField()),
                ('email_cc', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumberContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128)),
                ('ISD_code', models.CharField(max_length=128)),
                ('original_number', models.CharField(max_length=128)),
                ('formatted_number', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('confidence_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=512)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contact_application.emailinfo')),
                ('emails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_application.emailcontact')),
                ('phone_numbers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_application.phonenumbercontact')),
                ('web_sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_application.website')),
            ],
        ),
    ]
