# Generated by Django 4.2.3 on 2023-08-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SegregatedSkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField()),
                ('skill', models.CharField(unique=True)),
                ('ontology', models.CharField()),
                ('alias', models.CharField()),
                ('formatted_name', models.CharField()),
                ('evidence', models.CharField()),
                ('last_used', models.CharField()),
                ('experience_in_months', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_block', models.TextField()),
                ('skill_keywords', models.TextField()),
                ('segregated_skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skill_application.segregatedskillmodel')),
            ],
        ),
    ]
