# Generated by Django 4.2.3 on 2023-08-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='default_category')),
                ('sub_category', models.CharField(default='default_category')),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resume_file_name', models.CharField(max_length=256)),
                ('parsing_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_category', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cv_application.cvcategory')),
                ('file_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv_application.fileinfo')),
            ],
        ),
    ]
