# Generated by Django 4.2.3 on 2023-08-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country_application', '0001_initial'),
        ('cv_application', '0002_cvmodel_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='resume_country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='country_application.country'),
        ),
    ]
