# Generated by Django 4.2.3 on 2023-08-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_application', '0003_cvmodel_resume_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvmodel',
            name='resume_country',
        ),
    ]
