# Generated by Django 4.2.3 on 2023-08-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_application', '0004_remove_cvmodel_resume_country'),
        ('personal_info_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='personal_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='personal_info_application.personalinfomodel'),
            preserve_default=False,
        ),
    ]
