# Generated by Django 4.2.3 on 2023-08-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=128)),
                ('language_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('titled_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('formatted_name', models.CharField(max_length=128)),
                ('confidence_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(max_length=8)),
                ('father_name', models.CharField()),
                ('mother_name', models.CharField()),
                ('hobbies', models.TextField()),
                ('martial_status', models.CharField()),
                ('nationality', models.CharField()),
                ('objectives', models.TextField()),
                ('achievements', models.TextField()),
                ('language_known', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal_info_application.languagemodel')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal_info_application.namemodel')),
                ('resume_country', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='country_application.country')),
                ('resume_language', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resume_lang', to='personal_info_application.languagemodel')),
            ],
        ),
    ]
