# Generated by Django 4.2.3 on 2023-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, upload_to='', verbose_name='Аватарка')),
                ('fullname_ru', models.CharField(max_length=100, verbose_name='Имя')),
                ('fullname_en', models.CharField(max_length=100)),
                ('position_ru', models.CharField(max_length=200, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=200)),
                ('is_showed', models.BooleanField(default=True, verbose_name='Показывать в списке')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('show_email', models.BooleanField(default=False, verbose_name='Отображать почту')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['id'],
            },
        ),
    ]
