# Generated by Django 4.2.3 on 2023-08-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField()),
                ('formatted_name', models.CharField()),
                ('confidence_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('formatted_name', models.CharField()),
                ('alias', models.CharField()),
                ('related_skills', models.CharField()),
                ('confidence_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_skills', models.CharField()),
                ('project_name', models.CharField()),
                ('team_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_job_period', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('is_current_employer', models.BooleanField(default=False)),
                ('job_description', models.CharField()),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='experience_application.employer')),
                ('job_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='experience_application.jobprofile')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience_application.projects')),
            ],
        ),
    ]
