# Generated by Django 4.2.3 on 2023-08-15 13:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок новости')),
                ('title_image', models.FileField(blank=True, default=True, upload_to='', verbose_name='Картинка заголовка новости')),
                ('date_creation', models.DateTimeField(verbose_name='Дата создания новости')),
                ('is_published', models.BooleanField(default=False)),
                ('body', tinymce.models.HTMLField(default='')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-date_creation',),
            },
        ),
    ]
