# Generated by Django 4.2.3 on 2023-08-15 13:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_ru', tinymce.models.HTMLField(default='')),
                ('content_en', tinymce.models.HTMLField(default='')),
            ],
            options={
                'verbose_name': 'Контент страницы',
                'verbose_name_plural': 'Контент страницы',
            },
        ),
    ]
