# Generated by Django 4.2.3 on 2023-08-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_alpha2', models.CharField(default='-1', max_length=254)),
                ('iso_alpha3', models.CharField(default='-1', max_length=254)),
                ('UN_code', models.CharField(default='-1', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='unknown', max_length=256)),
                ('evidence', models.CharField(default='unknown', max_length=256)),
                ('country_code', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='country_application.countrycode')),
            ],
        ),
    ]
